language: cpp

sudo: required

compiler: gcc

before_install:
  - echo $LANG
  - sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev
  - gem update --system
  - gem --version
  - ln -s libglib-1.2.so.0.0.8 libglib.so
  - make clean
  - make HelloHackathon.sh
  - ./HelloHackathon.sh

before_script:
  - travis_retry ./configure --llvm-config llvm-config-3.4l

install: autoconf

deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: chiranjeevi.v.desaraju@verizon.com
  password: gundu1526
  organization: titus_hackathon_legends
  space: development
  on:
    repo: KrishnaHarishK/HelloCHackathon